language: generic

sudo: required

services:
  - docker

notifications:
  email: false

cache:
  directories:
    - turningpoint-convex

before_install:
  -
    if [ -e "turningpoint-convex/image.tar" ]; then
      docker load -i "turningpoint-convex/image.tar";
    else
      docker build -t "turningpoint-convex" -f Dockerfile .;
      mkdir -p "turningpoint-convex"; docker save -o "turningpoint-convex/image.tar" "turningpoint-convex";
    fi

script:
  - docker run -v `pwd`:/build/project "turningpoint-convex" sh -c 'make'
